# Generated by Django 3.2 on 2021-12-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=500)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('size', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('pattern', models.CharField(max_length=100)),
                ('colour1', models.CharField(max_length=100)),
                ('colour2', models.CharField(max_length=100)),
                ('colour3', models.CharField(max_length=100)),
                ('colour4', models.CharField(max_length=100)),
            ],
        ),
    ]
