# Generated by Django 3.2 on 2021-12-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_remove_customorder_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='size',
            field=models.CharField(default='', max_length=100),
        ),
    ]
