# Generated by Django 3.2 on 2021-12-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_customorder_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='pattern',
        ),
        migrations.AddField(
            model_name='customorder',
            name='pattern_name',
            field=models.CharField(blank=True, choices=[('Dreams', 'Dreams'), ('Sun', 'Sun'), ('Flower', 'Flower'), ('Ice', 'Ice'), ('Stripe', 'Stripe'), ('Granny', 'Granny'), ('Spiked Stripe', 'Spiked Stripe'), ('Lacy Sun', 'Lacy Sun'), ('Random Mix', 'Mix')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='colour1',
            field=models.CharField(choices=[('RED', 'Red'), ('OR', 'Orange'), ('GRN', 'Green'), ('BLU', 'Blue'), ('PI', 'Pink'), ('YE', 'Yellow'), ('TEA', 'Teal'), ('GRY', 'Grey'), ('PU', 'Purple'), ('TU', 'Turquoise'), ('BLA', 'Black'), ('WH', 'White'), ('CR', 'Cream'), ('BEI', 'Beige'), ('BR', 'Brown'), ('MR', 'Maroon')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='colour2',
            field=models.CharField(blank=True, choices=[('RED', 'Red'), ('OR', 'Orange'), ('GRN', 'Green'), ('BLU', 'Blue'), ('PI', 'Pink'), ('YE', 'Yellow'), ('TEA', 'Teal'), ('GRY', 'Grey'), ('PU', 'Purple'), ('TU', 'Turquoise'), ('BLA', 'Black'), ('WH', 'White'), ('CR', 'Cream'), ('BEI', 'Beige'), ('BR', 'Brown'), ('MR', 'Maroon')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='colour3',
            field=models.CharField(blank=True, choices=[('RED', 'Red'), ('OR', 'Orange'), ('GRN', 'Green'), ('BLU', 'Blue'), ('PI', 'Pink'), ('YE', 'Yellow'), ('TEA', 'Teal'), ('GRY', 'Grey'), ('PU', 'Purple'), ('TU', 'Turquoise'), ('BLA', 'Black'), ('WH', 'White'), ('CR', 'Cream'), ('BEI', 'Beige'), ('BR', 'Brown'), ('MR', 'Maroon')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='colour4',
            field=models.CharField(blank=True, choices=[('RED', 'Red'), ('OR', 'Orange'), ('GRN', 'Green'), ('BLU', 'Blue'), ('PI', 'Pink'), ('YE', 'Yellow'), ('TEA', 'Teal'), ('GRY', 'Grey'), ('PU', 'Purple'), ('TU', 'Turquoise'), ('BLA', 'Black'), ('WH', 'White'), ('CR', 'Cream'), ('BEI', 'Beige'), ('BR', 'Brown'), ('MR', 'Maroon')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='material',
            field=models.CharField(choices=[('AC', '100% Acrylic'), ('CN', '100% Cotton'), ('AW', '70% Acrylic, 30% Wool')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='size',
            field=models.CharField(choices=[('S', 'Small: 100cm x 100cm'), ('M', 'Medium: 190cm x 90cm'), ('L', 'Large: 135cm x 190cm'), ('XL', 'X Large: 150cm x 200cm')], default='S', max_length=20),
        ),
    ]
