# Generated by Django 3.2 on 2021-12-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0006_alter_customorder_design'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
