# Generated by Django 3.2 on 2021-12-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0007_alter_customorder_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='design',
            field=models.CharField(blank=True, choices=[('Dreams', 'Dreams'), ('Sun', 'Sun'), ('Flower', 'Flower'), ('Ice', 'Ice'), ('Stripe', 'Stripe'), ('Granny', 'Granny'), ('Spiked Stripe', 'Spiked Stripe'), ('Lacy Sun', 'Lacy Sun'), ('Random Mix', 'Mix')], default='Random Mix', max_length=100),
        ),
    ]
