# Generated by Django 3.2.9 on 2021-12-08 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('friendly_name', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('friendly_name', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('item_sizes', models.CharField(choices=[('OS', 'One Size'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='OS', max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('material', models.CharField(choices=[('AC', '100% Acrylic'), ('CN', '100% Cotton'), ('AW', '70% Acrylic, 30% Wool')], default='AC', max_length=2)),
                ('machine_wash', models.BooleanField(default=True)),
                ('product_image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('colour1', models.CharField(choices=[('RED', 'Red'), ('OR', 'Orange'), ('GRN', 'Green'), ('BLU', 'Blue'), ('PI', 'Pink'), ('YE', 'Yellow'), ('TEA', 'Teal'), ('GRY', 'Grey'), ('PU', 'Purple'), ('TU', 'Turquoise'), ('BLA', 'Black'), ('WH', 'White'), ('CR', 'Cream'), ('BEI', 'Beige'), ('BR', 'Brown'), ('MR', 'Maroon')], max_length=50)),
                ('colour2', models.CharField(blank=True, choices=[('RED', 'Red'), ('OR', 'Orange'), ('GRN', 'Green'), ('BLU', 'Blue'), ('PI', 'Pink'), ('YE', 'Yellow'), ('TEA', 'Teal'), ('GRY', 'Grey'), ('PU', 'Purple'), ('TU', 'Turquoise'), ('BLA', 'Black'), ('WH', 'White'), ('CR', 'Cream'), ('BEI', 'Beige'), ('BR', 'Brown'), ('MR', 'Maroon')], default='', max_length=50)),
                ('colour3', models.CharField(blank=True, choices=[('RED', 'Red'), ('OR', 'Orange'), ('GRN', 'Green'), ('BLU', 'Blue'), ('PI', 'Pink'), ('YE', 'Yellow'), ('TEA', 'Teal'), ('GRY', 'Grey'), ('PU', 'Purple'), ('TU', 'Turquoise'), ('BLA', 'Black'), ('WH', 'White'), ('CR', 'Cream'), ('BEI', 'Beige'), ('BR', 'Brown'), ('MR', 'Maroon')], default='', max_length=50)),
                ('colour4', models.CharField(blank=True, choices=[('RED', 'Red'), ('OR', 'Orange'), ('GRN', 'Green'), ('BLU', 'Blue'), ('PI', 'Pink'), ('YE', 'Yellow'), ('TEA', 'Teal'), ('GRY', 'Grey'), ('PU', 'Purple'), ('TU', 'Turquoise'), ('BLA', 'Black'), ('WH', 'White'), ('CR', 'Cream'), ('BEI', 'Beige'), ('BR', 'Brown'), ('MR', 'Maroon')], default='', max_length=50)),
                ('pattern_name', models.CharField(blank=True, default='', max_length=100)),
                ('designer', models.CharField(blank=True, default='', max_length=50)),
                ('can_custom_design', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('likes', models.ManyToManyField(blank=True, related_name='product_likes', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(blank=True, max_length=99, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.tag')),
            ],
        ),
    ]
