# Generated by Django 3.2.9 on 2021-12-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pattern_name',
            field=models.CharField(blank=True, choices=[('Dreams', 'Dreams'), ('Sun', 'Sun'), ('Flower', 'Flower'), ('Ice', 'Ice'), ('Stripe', 'Stripe'), ('Granny', 'Granny'), ('Spiked Stripe', 'Spiked Stripe'), ('Lacy Sun', 'Lacy Sun'), ('Mix', 'Mix')], default='', max_length=100),
        ),
    ]
