# Generated by Django 3.2 on 2021-12-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211208_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='can_custom_design',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
