# Generated by Django 3.2 on 2022-01-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220108_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='friendly_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
